---
title: "SVE Demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo_sve}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vaccine)
library(sl3)
```

Data from the HIV Vaccine Trials Network's (HVTN) 505 vaccine efficacy trial
comes bundled with the `vaccine` package. First, we load that example data,

```{r load_data}
data(hvtn505)
head(hvtn505)
attach(hvtn505)
```



```{r estimate_risk}
risk_est <- est_mtprisk(
  ve_dat = hvtn505,
  Y = "HIVwk28preunbl",
  S = "IgG_env",
  A = "trt",
  W = c("age", "BMI", "bhvrisk"),
  B = "casecontrol",
  delta_grid = seq(-0.5, 0.5, by = 0.25),
  estimator = "tmle",
  fluctuation = "weighted",
  weighting = "identity",
  ci_level = 0.95,
  ci_type = "marginal",
  gps_bound = 0.01,
  gps_est = sl3::Lrnr_density_semiparametric$new(
    mean_learner = sl3::Lrnr_glm_fast$new()
  ),
  or_est = sl3::Lrnr_glm_fast$new(),
  tps_est = sl3::Lrnr_glm_fast$new(),
  eif_est = "glm"
)
```

```{r estimate_sve}
sve_est <- est_sve(
  ve_dat = hvtn505,
  Y = "HIVwk28preunbl",
  S = "IgG_env",
  A = "trt",
  W = c("age", "BMI", "bhvrisk"),
  B = "casecontrol",
  delta_grid = seq(-0.5, 0.5, by = 0.25),
  estimator = "tmle",
  fluctuation = "weighted",
  weighting = "identity",
  ci_level = 0.95,
  ci_type = "marginal",
  gps_bound = 0.01,
  gps_est = sl3::Lrnr_density_semiparametric$new(
    mean_learner = sl3::Lrnr_glm_fast$new()
  ),
  or_est = sl3::Lrnr_glm_fast$new(),
  tps_est = sl3::Lrnr_glm_fast$new(),
  eif_est = "glm"
)
```

```{r vis_estimated_sve}
plot_sve(sve_est)
```

