on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: code-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
